# fly.toml app configuration file generated for budget-invest on 2025-09-01T23:47:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'budget-invest'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'budget_data'
  destination = '/ezbookkeeping/data'
